config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'

  resources :departments do 
    resources :items 
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    @departments = Department.all 
  end

  def show
  end

  def new
    @department = Department.new 
    render partial: "form"
  end

  def create
    @department = Department.new(departments_params)

    if @department.save 
      redirect_to departments_path 
    else 
      render partial: "form" 
    end 
  end 

  def edit
    render partial: "form"
  end

  def update 

    if @department.update(departments_params)
      redirect_to departments_path 
    else
      render partial: "form"
    end 
  end 

  def destroy
    @department.destroy 
    redirect_to departments_path
  end 

  private 
  def departments_params 
    params.require(:department).permit(:name)
  end 

  def set_department 
    @department = Department.find(params[:id])
  end 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]  
  
  def index
    @items = @department.items 
  end

  def show
    # render :show 
  end

  def new
    @item = @department.items.new 
    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)

    if @item.save
      redirect_to department_item_path(@department.id, @item.id)
    else 
      render partial: "form"
    end 
  end 

  def edit
    render partial: "form"
  end
  
  def update
    if @item.update(item_params)
      redirect_to department_item_path(@department.id, @item.id)
    else 
      render partial: "form"
    end 
  end 

  def destroy 
    @item.destroy 
    redirect_to department_items_path(@department.id)
  end 

  private 
  def set_department 
    @department = Department.find(params[:department_id])
  end 

  def set_item
    @item = Item.find(params[:id])
  end 

  def item_params 
    params.require(:item).permit(:name, :description, :price)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1> <%= @department.id ? "Edit Department" : "Create Department" %> </h1> 
<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1 class="center">The Department Store</h1>
<hr>
<h5>Here is a list of our departments:</h5>
<hr>
<br>
<%= link_to 'Create a new department', new_department_path, class:'btn purple lighten-2 white-text hoverable' %>
<ul>
  <% @departments.each do |department| %>
    <li><h4><%= link_to department.name, department_path(department.id), class:'btn purple lighten-2 white-text hoverable' %></h4></li>
  <% end %>
</ul>

app/views/departments/show.html.erb
<h1 class="center"><%= @department.name %></h1>
<hr />
<p class="center">What would you like to do?</p>
<hr>
<br>

<div class="btn-layout">
<%= link_to 'View Products', department_items_path(@department), class:'btn purple lighten-2 white-text hoverable' %>
<%= link_to 'Edit Department', edit_department_path(@department), class:'btn purple lighten-2 white-text hoverable' %>

<%= link_to 'Delete Department', @department, method: :delete, class:'btn purple lighten-2 white-text hoverable' %>

</div>
<%# <div class="back-btn"> %>
<%= link_to 'Back to Home', root_path, class:'back-btn btn purple darken-2 white-text hoverable' %>
<%# </div> %>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <br />

  <%= f.label :price %>
  <%= f.number_field :price, required: true, step: :any %> 

  <%= f.label :description %>
  <%= f.text_area :description, required: true %>


  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1> <%= @department.name %> Products </h1>
<%= link_to 'Create a new item', new_department_item_path(@department) %>
<br/>
<%= link_to 'Back to Department', department_path(@department) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, department_item_path(@department, item) %></li>
  <% end %>
</ul>

app/views/items/show.html.erb
<h1><%= @department.name %> - <%= @item.name %></h1>
<hr>
<p>$<%= '%.2f' % @item.price %></p>
<p><%= @item.description %></p>
<%= link_to 'Edit Item', edit_department_item_path([@department, @item]) %>
<%= link_to 'Delete Item', [@department, @item], method: :delete %>
<%= link_to 'Back To Items', department_items_path(@department) %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Departments', root_path, class:'btn purple lighten-2 white-text hoverable' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="container">
    <nav>
    <div class="nav-wrapper #9fa8da indigo lighten-3">
      <ul id="nav-mobile" class="left hide-on-med-and-down">
         <%= render 'layouts/navbar' %>
      </ul>
    </div>
    </nav>
    <%= yield %>
  </body>
</html>